#ddev-generated
# PHP_CodeSniffer & WordPress Coding Standards add-on for DDEV
services:
  wp-phpcs-wpcs:
    container_name: ddev-${DDEV_SITENAME}-wp-phpcs-wpcs
    image: busybox:stable
    command: tail -f /dev/null
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
    - "ddev-global-cache:/mnt/ddev-global-cache"
